AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: register_user
      Handler: lambda_handler.lambda_handler
      Runtime: python3.8
      Events:
        RegisterUserAPI:
          Type: Api
          Properties:
            Path: /register_user
            Method: any
